# Generated by Django 2.1.3 on 2019-01-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0004_auto_20190129_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='selectec',
            field=models.BooleanField(default=False),
        ),
    ]
