# Generated by Django 2.1.3 on 2019-01-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0005_image_selectec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='selectec',
            new_name='selected',
        ),
    ]
