# Generated by Django 2.1.3 on 2019-01-31 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0006_auto_20190130_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='photo',
        ),
    ]
