# Generated by Django 2.1.3 on 2019-02-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0007_auto_20190131_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='max_photos',
            field=models.IntegerField(default=0),
        ),
    ]
