# Generated by Django 2.1.3 on 2019-02-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0010_auto_20190206_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
