# Generated by Django 2.1.3 on 2019-02-07 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album_app', '0012_remove_comment_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='album',
        ),
        migrations.AddField(
            model_name='avatar',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to=settings.AUTH_USER_MODEL),
        ),
    ]
