# Generated by Django 2.1.7 on 2019-03-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0017_auto_20190306_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='album_app.Album'),
        ),
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='album_app.Album'),
        ),
    ]
