# Generated by Django 2.1.7 on 2019-03-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0018_auto_20190306_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='participants',
            field=models.ManyToManyField(to='album_app.Profile'),
        ),
    ]
