# Generated by Django 2.1.7 on 2019-03-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0019_album_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='participants',
            new_name='profiles',
        ),
    ]
