# Generated by Django 2.1.7 on 2019-03-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0020_auto_20190311_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='album_app.Profile'),
        ),
    ]
