# Generated by Django 2.1.7 on 2019-03-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0022_album_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='album',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='album',
        ),
        migrations.RemoveField(
            model_name='image',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
